pairing_gen:	pairing_gen.c modulo.o poly.o
	gcc -o pairing_gen pairing_gen.c modulo.o poly.o -lgmp -lm

pairing_sweep:	pairing_sweep.c 
	gcc -o pairing_sweep pairing_sweep.c -lgmp -lm

pairing_phi6: pairing_phi6.c
	gcc -o pairing_phi6 pairing_phi6.c -lgmp

